package com.emberjs.cli

import com.intellij.ide.util.projectWizard.WebTemplateNewProjectWizard
import com.intellij.ide.wizard.GeneratorNewProjectWizardBuilderAdapter


class EmberCLIProjectModuleBuilder: GeneratorNewProjectWizardBuilderAdapter(WebTemplateNewProjectWizard(EmberCliProjectGenerator()))